
export const gif = ["./gifs/1.gif", "./gifs/dog.gif", "./gifs/llama.gif", "./gifs/sad.gif", "./gifs/sheep.gif", 
    "./gifs/tractor.gif", "./gifs/giphy (1).gif",
    "./gifs/giphy (2).gif", "./gifs/giphy (3).gif",
    "./gifs/giphy (4).gif", "./gifs/giphy (5).gif",
    "./gifs/giphy (6).gif", "./gifs/giphy (7).gif",
    "./gifs/giphy (8).gif", "./gifs/giphy (9).gif",
    "./gifs/giphy (10).gif", "./gifs/giphy (11).gif",
    "./gifs/giphy (12).gif", "./gifs/giphy (13).gif",
    "./gifs/giphy (14).gif", "./gifs/giphy (15).gif",
    "./gifs/giphy (16).gif", "./gifs/giphy (17).gif",
    "./gifs/giphy (18).gif", "./gifs/giphy (19).gif",
    "./gifs/giphy (20).gif", "./gifs/giphy (21).gif",
    "./gifs/giphy (22).gif", "./gifs/giphy (23).gif",
    "./gifs/giphy (24).gif", "./gifs/giphy (25).gif",
    "./gifs/giphy (26).gif", "./gifs/giphy (27).gif",
    "./gifs/giphy (28).gif", "./gifs/giphy (29).gif",
    "./gifs/giphy (30).gif", "./gifs/giphy (31).gif",
    "./gifs/giphy (32).gif", "./gifs/giphy (33).gif",
    "./gifs/giphy (34).gif", "./gifs/giphy (35).gif",
    "./gifs/giphy (36).gif", "./gifs/giphy (37).gif",
    "./gifs/giphy (38).gif",
    // "./gifs/giphy ().gif", "./gifs/giphy ().gif",
    // "./gifs/giphy ().gif", "./gifs/giphy ().gif",
    
];