
export const quoteImg = [
    
    {frase: "Yo estaba en la disco perreando y con ella me enredé", img: "./images/anuel.jpg"},
    {frase: "Tú eres una hipocrita, un día me amas y otro día me odias", img: "./images/anuel.jpg"},
    {frase: "Ella quiere beber, ella quiere bailar, su novio la dejó y lo quiere olvidar", img: "./images/anuel.jpg"},
    {frase: "Bebesita, tu hombre te ama pero tu le eres infiel", img: "./images/anuel.jpg"},
    {frase: "Qué tengo que hacer pa' que tu seas mi mujer", img: "./images/anuel.jpg"},
    {frase: "Dicen que soy un delincuente, el rifle siempre en mi casa", img: "./images/anuel.jpg"},
    {frase: "Bebesita odio cuando tu te vas, pero por tus nalgas a mi me encanta verte ir", img: "./images/anuel.jpg"},
    {frase: "Lo de nosotros es un secreto, que nadie se entere", img: "./images/anuel.jpg"},
    {frase: "Salió temprano a janguear pa pasarla bien y portarse mal", img: "./images/anuel.jpg"},
    {frase: "Déjame entrar como antes, cuando tú y yo eramos amantes", img: "./images/anuel.jpg"},
    {frase: "Tu ere' una diabla y yo soy un demonio, yo amo tu totito pero a ti te odio", img: "./images/anuel.jpg"},
    {frase: "A-L-E-M-AN, ya valió verga Alemán ahí viene", img: "./images/aleman.jpg"},
    {frase: "Ey, MC's de fábrica. Aquí rockeamos duro, como si fuera Metallica", img: "./images/aleman.jpg"},
    {frase: "El día que me muera y esté en la cruz, en mi funeral que suene Gin&Juice", img: "./images/aleman.jpg"},
    {frase: "Millones de monjas están pidiendo el satisfyer, le rezan a Dios y le agradecen el detalle", img: "./images/ayax.jpg"},
    {frase: "Salgo con el cora roto, no lo notas? Yo lo noto", img: "./images/ayax.jpg"},
    {frase: "Compadre, soy el motivo para suicidarte", img: "./images/ayax.jpg"},
    {frase: "A veces se me pasa, a veces paso", img: "./images/ayax.jpg"},
    {frase: "L'enfant terrible, solo lo hago pa' que el corazón me vibre", img: "./images/ayax.jpg"},
    {frase: "Estaba tan solo en aquel desierto extraño, que abracé a ese cactus aunque me hiciera daño", img: "./images/ayax.jpg"},
    {frase: "Ya me acostumbré, a ganar como el 23", img: "./images/arcangel.jpg"},
    {frase: "Hola llegué, bajé con unas botas Bottega Vené", img: "./images/arcangel.jpg"},
    {frase: "Y no te voy a envolver, sé que lo hacemos y tu vas a volver", img: "./images/anitta.jpg"},
    {frase: "5 la mañana en el estudio haciendo Teca", img: "./images/asan.jpg"},
    {frase: "Yo soy México y me levanto como en el 85", img: "./images/aczino.jpg"},
    // {frase: "", img: "./images/acru.jpg"},
    {frase: "Hoy estoy pa' ti, yo te vo'a costear", img: "./images/almighty.jpg"},
    {frase: "Nadie como tu me conoce, yo no sé a quién llamo cuando lleguen las 12", img: "./images/anaMena.jpg"},
    {frase: "Solo tú te va a quedar, con una mano alante y otra mano atrás", img: "./images/anaMena.jpg"},
    {frase: "Dice que mi bicho esta cabrón", img: "./images/badbunny.jpg"},
    {frase: "Estoy activo 24/7, conmigo no hacen falta los juguetes", img: "./images/badbunny.jpg"},
    // {frase: "", img: "./images/badbunny.jpg"},
    // {frase: "", img: "./images/badbunny.jpg"},
    // {frase: "", img: "./images/badbunny.jpg"},
    // {frase: "", img: "./images/badbunny.jpg"},
    // {frase: "", img: "./images/badbunny.jpg"},
    // {frase: "", img: "./images/badbunny.jpg"},
    // {frase: "", img: "./images/badbunny.jpg"},
    // {frase: "", img: "./images/badbunny.jpg"},
    // {frase: "", img: "./images/badbunny.jpg"},
    {frase: "A mi me gustan mayores, de esos que llaman señores", img: "./images/beckyG.jpg"},
    {frase: "Si tu me llamas, nos vamos pa' tu casa", img: "./images/beckyG.jpg"},
    {frase: "Baby hoy no vamos a dormir", img: "./images/beckyG.jpg"},
    {frase: "Tu me robaste el corazón como un criminal", img: "./images/beckyG.jpg"},
    {frase: "El es el fulanito, que me tiene loca a mi", img: "./images/beckyG.jpg"},
    {frase: "Lo que se va se va, conmigo no te equivoques", img: "./images/beckyG.jpg"},
    {frase: "Y cuando te besé, sentí que toqué el cielo. Y no me equivoqué, porque lo haría de nuevo", img: "./images/beckyG.jpg"},
    {frase: "Pa' atrás, pa' atrás, este culito lo heredé de mi mamá", img: "./images/beckyG.jpg"},
    {frase: "Quien te controla, tu naciste pa' morir sola", img: "./images/brytiago.jpg"},
    {frase: "No voy a negarte que bien dura te ves, puede ser que borracho vuelva un día y te de", img: "./images/brytiago.jpg"},
    {frase: "Por eso es que yo ando con mi ganga, al armero le compramo lo R y lo AK", img: "./images/bryantMyers.jpg"},
    {frase: "Y me hace tanta falta un beso tuyo, que me llames borracha pa' que te de bien duro", img: "./images/bryantMyers.jpg"},
    {frase: "Siempre ando fres-ko, sin ver lo que diga el resto", img: "./images/bhavi.jpg"},
    // {frase: "", img: "./images/bluntedVato.jpg"},
    // {frase: "", img: "./images/bigSoto.jpg"},
    {frase: "Esto c'est fini pa' Finisterre", img: "./images/bejo.jpg"},
    {frase: "Me gusta el dinero liso no doblao", img: "./images/benyJr.jpg"},
    {frase: "En la ST con el BJ, centro campo como Oka Jay", img: "./images/benyJr.jpg"},
    {frase: "El paquete es eme, mis enemigos a mi me temen, 4 motores pa' que reme", img: "./images/benyJr.jpg"},
    {frase: "Uh na na na, mientras empujas ese booty pa' atrás", img: "./images/cTangana.jpg"},
    {frase: "Tú me dejaste de querer cuando menos lo esperaba", img: "./images/cTangana.jpg"},
    {frase: "Me maten si no pueden entrar, me muera, no les puedo fallar. Yo sin esta gente, ¿pa' qué cojones quiero pasar?", img: "./images/cTangana.jpg"},
    {frase: "Perdí mis amigos, que le jodan al dinero quiero estar contigo", img: "./images/cTangana.jpg"},
    {frase: "Tirando billetes de 100, en un culo que no sé de quién", img: "./images/cTangana.jpg"},
    {frase: "Venga sube, te pago el Uber", img: "./images/cTangana.jpg"},
    // {frase: "", img: "./images/ca7riel.jpg"},
    {frase: "Andamo' burlao, al inivierno lo puse caliente, échate pal lao", img: "./images/cazzu.jpg"},
    {frase: "Se pasa de chivirika, y el culo suena 'pla-pla' la shorty e' de revista", img: "./images/chucky73.jpg"},
    {frase: "Nena dime si tú 'tás pa' mí, como yo estoy puesto pa' ti, te llevo una noche a Medellín y te pago el gym", img: "./images/crisMj.jpg"},
    {frase: "Ya no fuma mari sola, que yo, unos pitito', te puedo enrolar", img: "./images/crisMj.jpg"},
    {frase: "Tres perras, me esperan, creo que una era tu mujer, negga", img: "./images/cro.jpg"},
    {frase: "Soy hijo e' la noche, que me maneje ella. Soy su copiloto, vamo' de viaje a la estrella", img: "./images/cro.jpg"},
    {frase: "Voy pal mall, miro cuál quiero... mmm ", img: "./images/daniRiba.jpg"},
    {frase: "Antes era un pobre infeliz. Ahora no soy feliz pero ya no soy pobre", img: "./images/daniRiba.jpg"},
    // {frase: "", img: "./images/dano.jpg"},
    {frase: "El patio de tu casa huele a flores y pinta el barrio de colores", img: "./images/delaossa.jpg"},
    {frase: "Pero sigo en el barrio, en la placita, bajo temprano con mi prenda favorita", img: "./images/delaossa.jpg"},
    {frase: "Cuando yo era mocoso ya quería un Ferrari, hoteles con jacuzzi, pila de mamis", img: "./images/dicc.jpg"},
    {frase: "Get the bag, do the dash, dudade-de-de. Ey, ser rico e' complicado, pvta, mucho estrés", img: "./images/dillom.jpg"},
    {frase: "Oye que te ha pasao? Que me han contao que vas de capo y que te han robao", img: "./images/dollarselmouni.webp"},
    {frase: "Chacho, no voy borracho voy colocao, estoy esperando algo que me quite este pecao", img: "./images/dollarselmouni.webp"},
    {frase: "Cuando quieras llamame al cell, que yo te apago el fuego como haciamos antes", img: "./images/donP.jpg"},
    {frase: "Que tengo que hacer pa' que vuelvas conmigo", img: "./images/daddy.jpg"},
    {frase: "Contigo la pasé muy bien, quizás esto ni fue real, no te lo voy a negar, no te puedo sacar de mi mente", img: "./images/daddy.jpg"},
    {frase: "Con calma, yo quiero ver como ella lo menea", img: "./images/daddy.jpg"},
    {frase: "Cuando yo la vi, dije si esa mujer fuera para mí", img: "./images/daddy.jpg"},
    {frase: "Yo me quiero ir pa' casa pero tú no me deja, ese culo e' una amenaza, ya me creo que eres mi pareja", img: "./images/daddy.jpg"},
    {frase: "Y bailamos sin culpa, que yo sé que en el fondo te gusta", img: "./images/drefQ.jpg"},
    {frase: "Mami ven agarrame la mano sentí el calor de como todos nos miran, que si al menos vos estás a mi lado se me hace más fácil afrontar esa vida", img: "./images/duki.webp"},
    {frase: "Me puse la Gucci con un short de Nike, buzo y cadena, estoy que goteo", img: "./images/duki.webp"},
    {frase: "Adentro del pary, afuera en la calle se escucha mi voz", img: "./images/duki.webp"},
    {frase: "Tengo a los mios hablando italiano, de lunes a viernes solo comen pasta", img: "./images/duki.webp"},
    {frase: "Sabe que la quiero pero she don't give a fo", img: "./images/duki.webp"},
    {frase: "Llegando al sol, baby I'm a star boy ", img: "./images/duki.webp"},
    {frase: "Pvta vine a ganar todo like Lebron", img: "./images/duki.webp"},
    {frase: "Pasao de Kiii como Gokuuu, con mucha weed, con do' cu'", img: "./images/duki.webp"},
    //{frase: "", img: "./images/duki.webp"},
    {frase: "Soy de la clase humana que nació para ser el bosque no la' rama'", img: "./images/ecko.jpg"},
    {frase: "Tú, me gustas natural, acabá de levantar sin maquillar", img: "./images/eladio.jpg"},
    {frase: "Cuatro Rollie, dos AP. Young rich nigga como Mbappé", img: "./images/eladio.jpg"},
    {frase: "Flow fuera del planeta, no, no soy de Plutón. Soy de la H, no estoy hablando de Houston. De la cabeza a pies filotea'o de Louis Vuitton. Frontean de hotele' y to's son de Groupon", img: "./images/eladio.jpg"},
    {frase: "Yo sigo fly, como vuelo. Un helao' mira mi hielo. Bien high, como el cielo.", img: "./images/eladio.jpg"},
    {frase: "Acelerao yo voy sin frenos, tu me llamas y nos vemos", img: "./images/eladio.jpg"},
    {frase: "Vamo' hacerlo como si no importara, como como si el mundo se acabara", img: "./images/emiliaMernes.jpg"},
    {frase: "Mientras va al party sube un video, se pone perra para el perreo", img: "./images/emiliaMernes.jpg"},
    {frase: "Toy a nada de comprarme la chain, hace mucho estoy vistiendo Chanel", img: "./images/emiliaMernes.jpg"},
    {frase: "Amén, tamo' bendecia. En el nombre del padre y de toda las gatas mías", img: "./images/emiliaMernes.jpg"},
    {frase: "El roncito sabor madera, fernandito malamanera. Salgfo del metro y me enciendo una palmera, que bonita es la mañana cuando hay alguien que te espera", img: "./images/fernandoC.jpg"},
    {frase: "El niño del guero, se busca el dinero. Los niños del barrio, no tienen horario", img: "./images/fernandoC.jpg"},
    {frase: "Hasta cuandooo, voy a ver a mis niños tirititaando", img: "./images/fernandoC.jpg"},
    {frase: "Salud, un chorrito pa' las animas", img: "./images/feid.jpg"},
    {frase: "Normal si te sientes solita y me extrañas, y se te sale mi nombre", img: "./images/feid.jpg"},
    {frase: "Tu y yo bebe, haciendo de todo. Tú estas pa andar con este gato, no con ese pirobo", img: "./images/feid.jpg"},
    {frase: "Pero la miro y me acuerdo de ti. No se como explicarte lo que sentí. Salgo todos los dias pa la calle pa ver si te veo por ahí", img: "./images/feid.jpg"},
    // {frase: "", img: "./images/farina.jpg"},
    {frase: "Vivo like boss, toy' cocinando Holly con tu hoe", img: "./images/frijo.jpg"},
    {frase: "La puse a rezar y ella no cree en Dios", img: "./images/frijo.jpg"},
    {frase: "Dicen que soy un delincuente, por ahí la gente es lo que habla", img: "./images/farruko.jpg"},
    {frase: "Pepa' y agua pa' la seca, to el mundo en pastilla' en la discoteca", img: "./images/farruko.jpg"},
    // {frase: "", img: "./images/homerElMeroMero.jpg"},
    {frase: "Se hace la que no me conoce, pero en mi cama se volvió un vicio como la 5 doce", img: "./images/jhayCortez.jpg"},
    {frase: "Baby hoy estoy pa' ti, yo te vo'a costear. Me hablaron de ti, que te gusta frontear", img: "./images/jhayCortez.jpg"},
    {frase: "Así, pégate. Así, déjate. Easy. No la pongas tan difícil. Esto e' easy, esto e' fácil", img: "./images/jhayCortez.jpg"},
    {frase: "Con toa' la suya en la discoteca, se acabó la ley seca", img: "./images/jhayCortez.jpg"},
    {frase: "Tú ta' dura sin ir al gym, taco' Louboutin", img: "./images/jhayCortez.jpg"},
    {frase: "Cómo se siente? Cómo se siente? Baby del uno al diez yo te doy un 20", img: "./images/jhayCortez.jpg"},
    {frase: "Nadie lo hace como tú lo sabes hacer, ese cuerpito no e' mío pero yo le soy fiel", img: "./images/jhayCortez.jpg"},
    {frase: "No hay excusa, gasté 30k en la medusa", img: "./images/jhayCortez.jpg"},
    {frase: "Y tengo un culo nuevo. En un Airbnb con ella me encuevo. Las babys se van en uber, yo nunca las llevo. A tí te compre de to así que na te debo", img: "./images/jhayCortez.jpg"},
    {frase: "Te tenía a tí pero ahora quiero una Beyonce. En bikini pa pasarle el bronzer. Y otra nueva pa cuando salga del concert", img: "./images/jhayCortez.jpg"},
    // {frase: "", img: "./images/jhayCortez.jpg"},
    {frase: "c90 c90, llegando al pary en la c90", img: "./images/johnC.jpg"},
    {frase: "Yoo soy loco cuando lo mueve así, duro encima de mi", img: "./images/justinQuiles.jpg"},
    {frase: "Qué pretendes tú, llamándome a esta hora? Esa actitud la conozco ya", img: "./images/jBalvin.jpg"},
    {frase: "Y si hay humo en el ambiente, se pone demente y no quiere parar, me saca su instinto animal", img: "./images/jBalvin.jpg"},
    {frase: "Si necesita Reggaeton dale, sigue bailando mami no pare'", img: "./images/jBalvin.jpg"},
    {frase: "De lo tóxico que eres se volvió perjudicial", img: "./images/karolG.jpg"},
    {frase: "Hace rato que no sé nada de ti, taba' con alguien pero ya estoy free", img: "./images/karolG.jpg"},
    {frase: "Estaba loca por probarte, darte los besitos yo", img: "./images/karolG.jpg"},
    {frase: "Bebé qué fue, no pues que muy tragaito. Qué haces buscando melao, si sabes que yo errores no repito", img: "./images/karolG.jpg"},
    {frase: "Y mientras me curo del corazón, hoy salgo pal mar a aprovechar que hay sol", img: "./images/karolG.jpg"},
    {frase: "Juré que no me iba a coger de ningún culito, y aquí me tienes hablandote bonito", img: "./images/karolG.jpg"},
    {frase: "Que chimba se siente, hacer el amor con otro, y que quede entre nosotros. Tú eres mío sin papeles y así cero corazones rotos", img: "./images/karolG.jpg"},
    {frase: "Ya no tiene excusas, hoy salió con su amiga dice que pa' matar la tusa", img: "./images/karolG.jpg"},
    {frase: "Me siento grande por ti, y aunque lo intentara no podría sin ti", img: "./images/karolG.jpg"},
    {frase: "Me siento el progenitor de una gran prole, el profesor loco el preferido del cole", img: "./images/kaseO.jpg"},
    {frase: "Yo quisiera palmera en frente del mar y que mi trabajo fuera: estar y no pensar en respirar siquiera", img: "./images/kaseO.jpg"},
    {frase: "La vida es simple, recibes de lo que has dado y para ser feliz tan solo hay que olvidar el pasado ", img: "./images/kaseO.jpg"},
    {frase: "Y la fórmula funciona, la tele ilusiona, coma, drogan a la persona, luego lo difícil es no volverse loco, porque no hay moda que cure la soledad, ", img: "./images/kaseO.jpg"},
    {frase: "Ballantines, vida perdida por la mujer y la bebida", img: "./images/kaseO.jpg"},
    // {frase: "", img: "./images/kevinRoldan.jpg"},
    {frase: "Es una loca, me manda video al Snap mientra se toca", img: "./images/khea.jpg"},
    {frase: "¿Y dónde estás? Que hoy voy a buscarte. Para recordarte lo que alguna vez fuimos tú y yo", img: "./images/khea.jpg"},
    {frase: "Ayer me llamó mi ex y me dijo que el novio que tiene ahora es aburrido", img: "./images/khea.jpg"},
    {frase: "Cambie el amor por la marihuana, culos de putero, relojes, cubanas Philis a la mañana, discos por semana, mas fama mas drama mas putas me llaman", img: "./images/khea.jpg"},
    {frase: "Ando metido en mi movie-movie, por el money I'm a thot. Más dinero para ese booty, más problemas con la autorida'", img: "./images/kiddKeo.jpg"},
    {frase: "Ella, e' como las estrellas. Sé, que sus ojos me atropellan. Tam-bién, hace la vida más bella", img: "./images/kiddoToto.jpg"},
    // {frase: "", img: "./images/kinderM.jpg"},
    // {frase: "", img: "./images/lali.jpg"},
    {frase: "No' vamo' de borondo en la Ducati. Quiere meneo ese culo illuminati", img: "./images/laloEbratt.jpg"},
    {frase: "Y arranco al toque roque", img: "./images/Lgante.jpg"},
    {frase: "Quisiera que salgas de mi cabeza. No puedo dormirme soñarte me estresa", img: "./images/litKillah.jpg"},
    {frase: "Yo soy Lola Bunny. Be my Bugs, Bugs Bunny. A ti te gusta el party. Tú Clyde y Yo Bonnie", img: "./images/lolaIndigo.jpg"},
    {frase: "Yo ya no quiero na'", img: "./images/lolaIndigo.jpg"},
    {frase: "Toy contando ticket ticket como Jimmy Fallon", img: "./images/lucho.jpg"},
    {frase: "Yo si ando blessed, pese a quien le pese. Y al que no le guste, es porque de esto carece", img: "./images/lucho.jpg"},
    {frase: "Estar soltera está de moda, por eso ella no se enamora", img: "./images/lunay.jpg"},
    {frase: "Dime cómo le hago ahora, pa poderte tenerte a solas", img: "./images/lunay.jpg"},
    {frase: "La noche se presta pa' una aventura, tu y yo debajo la luna", img: "./images/lunay.jpg"},
    {frase: "Amor, si jugasemos tu policía y yo ladrón, solamente te pediría una condición, de no ser un juguete más para tu colección, que tengas compasión", img: "./images/maka.jpg"},
    {frase: "El aire me lleva, a sitios que no conozco, sueño con la plazuela. La magía que entre nosotros, las penas son menos penas", img: "./images/maka.jpg"},
    {frase: "Siempre que amanece pido a Dios, que dé a los míos to lo que se merecen", img: "./images/maka.jpg"},
    {frase: "Yo no vengo de La Habana, yo vengo del callejón. Del barrio del Almanjáyar, donde reside el sabor", img: "./images/maka.jpg"},
    {frase: "Estaba muerto y tu a mi me diste la vida, vida, tu a mi me diste la vida", img: "./images/maka.jpg"},
    {frase: "Son cositas del amor, son cositas del amor. Hoy tú te mueres por mi, mañana muero por ti yo", img: "./images/maka.jpg"},
    {frase: "La vida es hermosa cuando te das cuenta de las cosas, le das valor a los que te quieren, lo material se va como viene", img: "./images/maka.jpg"},
    {frase: "Puede que no te haga falta na', aparentemente na'. Hawai de vacaciones, mis felicitaciones", img: "./images/maluma.jpg"},    
    {frase: "Y si con otro pasas el rato, vamo' a ser feliz, vamo' a ser feliz, felices los 4", img: "./images/maluma.jpg"}, 
    {frase: "El cuarto huele a Christian Dior, eres muy bonita pa' llorar por él", img: "./images/maluma.jpg"}, 
    {frase: "Quiere salir, fumar, beber, subir un video pa' que lo vea él", img: "./images/maluma.jpg"},  
    {frase: "Ando manejando por las calles que me besaste, oyendo las canciones que un día me dedicaste", img: "./images/manuelTurizo.jpg"},
    {frase: "Te bloquee de Insta pero por otra cuenta veo tus historias", img: "./images/manuelTurizo.jpg"},
    {frase: "Tu número lo borré, no sé pa' qué si me lo sé de memoria", img: "./images/manuelTurizo.jpg"},
    {frase: "Dije que te olvidé, pero no te había olvidao ey ey ey, también dije que te superé y no te había superao", img: "./images/manuelTurizo.jpg"},
    {frase: "Voy buscando una lady, como tú la quiero así. Quiero que te enamores como estoy yo de ti", img: "./images/manuelTurizo.jpg"},
    {frase: "Dale  miénteme, haz  lo  que  tú  quieras  conmigo. Dime  que  esta  noche  yo soy  tu  bebé, y  mañana  somos  amigos,  amigos", img: "./images/mariaBecerra.jpg"},
    {frase: "Te di lo que tenía y no fue suficiente. Tu solo mentías y yo tu fiel creyente", img: "./images/mora.jpg"},
    {frase: "Salió a misionar, modelito, ella en mi cama quiere audicionar", img: "./images/mora.jpg"},
    {frase: "Hoy borro tu memoria, tu contacto y to' tus video'. Llegó el final de esta historia, no te arrepientas porque ya no te creo", img: "./images/mora.jpg"},
    {frase: "Y a vece' estaba bien, pero me hacía daño. Tú no eres real, baby, tú ere' un engaño", img: "./images/mora.jpg"},
    {frase: "Yo la vivo a mi manera, y cuando me muera to' los parlante' pa' afuera. Se prende el partyson en la vereda, las motora' patinando en la acera. E-E-Esto no termina, que nadie quede afuera", img: "./images/mesita.jpg"},
    {frase: "No fuimo' a fuego, me compré un paragua', y pa' lo' pato' aguacero. Llamó por la internet, yo le doy fuego. Soy un tigre de mal desarma como un Lego. Así te quiero", img: "./images/mesita.jpg"},
    {frase: "Dans la capi comme Messi, Messi, Messi", img: "./images/mhd.jpg"},
    {frase: "Y si traes la codeina ina ina ina, que no te olvides de la lima", img: "./images/midel.jpg"},
    {frase: "Empezaron en la calle con cuzi cuza. Lo tenía un grupo como la Yakuza", img: "./images/morad.jpg"},
    {frase: "Y yo no te quiero insistir, pero si veo algo tuyo en las rede' lo noto", img: "./images/morad.jpg"},
    {frase: "Discoteca siempre en chándal como banda organizada. Hablan siempre del Morad pero de frente no es nada", img: "./images/morad.jpg"},
    {frase: "Y te sueño y aparece' en mi cabeza. Y en sueño' coges y me besa'. Y dime qué dirá, y dime qué dirá", img: "./images/morad.jpg"},
    {frase: "En su mesa comerán los que con él pasaron hambre", img: "./images/morad.jpg"},
    {frase: "Las palabras sólo sirven pa' escucharlas, así que, a mí no me des más charla", img: "./images/morad.jpg"},
    {frase: "Yo no voy de mafioso, y no sé que te pasa. Yo sé que te molesta, que sonemos hasta en tu casa", img: "./images/morad.jpg"},
    {frase: "Dime donde paras, para ir a buscarte, y cogerte aparte. ¿Dónde está' escondío? A mí no interesa", img: "./images/morad.jpg"},
    {frase: "Que no me la creío y tampoco me la dao mi intencion nunca sio nunca ser el aclamao. La atencion ni si quiera la aviamos buscao", img: "./images/morad.jpg"},
    {frase: "No tenía para entrar en las tiendas, dudo que ese mundo tú ya lo entiendas", img: "./images/morad.jpg"},
    {frase: "Los duro' llevan Motorola, van con motora. La chulería no les mola y no hablan de pistola'", img: "./images/morad.jpg"},
    {frase: "He visto la muerte de gente del barrio que nadie se acuerda de ello'. He visto a gente ayudando en dinero y no tiene cadena' en el cuello", img: "./images/morad.jpg"},
    {frase: "Que yo nunca he sali'o del ghetto, el ghetto tampoco salió de mí", img: "./images/morad.jpg"},
    {frase: "Siempre que amanece o haga sol, tengo a mi madre pidiéndole al de arriba. Que todo lo que pase sea mejor y que lo malo solo sea fatiga", img: "./images/morad.jpg"},
    {frase: "Por el tiempo no' cansa, por vida que no pesa. Dinero pa' la casa, pa' quitar de pobreza", img: "./images/morad.jpg"},
    {frase: "Hablan pero na', na', na', na'. Parece que esto les duele, sonando de la nada, famosos y la tele", img: "./images/morad.jpg"},
    // {frase: "", img: "./images/mozartL.jpg"},
    {frase: "La mai también está dura y eso ella lo va a heredar", img: "./images/mykeTowers.jpg"},
    {frase: "Y ya le explotó la EQUIX, shaky morena shaky", img: "./images/mykeTowers.jpg"},
    {frase: "Alza la mano si tu fumas marihuana, pasame el lighter que yo quiero prender", img: "./images/mykeTowers.jpg"},
    {frase: "Piensan que ya no estoy contigo, por que yo no la sigo, la llamo y no la escribo y si supieran las cosas que hacemo' cuando no hay testigos", img: "./images/mykeTowers.jpg"},
    {frase: "La curiosidad me mata y no aguanto, ya te quiero tener sólo dime cuándo", img: "./images/mykeTowers.jpg"},
    {frase: "I am a nasty girl fantastic, este culo es natural no plastic", img: "./images/nathy.jpg"},
    // {frase: "", img: "./images/natosWaor.jpg"},
    {frase: "Y ahora todos tiran beef. Yo los vi, son más de dos. Pero eso no es trap, 'manito, trap es mi negro en prisión. Trap no son tus putas, trap es mi equipo tumbando el club", img: "./images/neoPistea.png"},
    // {frase: "", img: "./images/neutroS.jpg"},
    {frase: "Colocaaaao como Drakeeee, fumo solo para quitar el estrés", img: "./images/nicki.jpg"},
    {frase: "All eyes on me. Llámame cuando sientas que lo nuestro está perdío, solamente estoy pa ti", img: "./images/nicki.jpg"},
    {frase: "Te estaba buscando, por la calle gritando, como un loco tomando", img: "./images/nickyJam.jpg"},
    {frase: "Yo quiero la combi completa, chocha culo teta", img: "./images/nickyJam.jpg"},
    {frase: "Lo que dicen en la calle sobre mi, y no te voy anegar", img: "./images/nickyJam.jpg"},
    {frase: "El biza la soltó y sonó cabron, la baby la probó y se enamoró", img: "./images/nickyJam.jpg"},
    // {frase: "", img: "./images/ñengo.jpg"},
    // {frase: "", img: "./images/obieW.jpg"},
    {frase: "Mira que te dije que sin avisar la llama del amor, crece y no mengua", img: "./images/omarMontes.jpg"},
    {frase: "Pero me tienes alocao, intentando pero no consigo, dime baby si te vienes conmigo, dale nena caile a mi cama a mi cama", img: "./images/omarMontes.jpg"},
    {frase: "La vi bailando en la Alhambra, una gitana mora guapa. Le vi sus ojos y me enamoré, con su cara morena yo me la llevé", img: "./images/omarMontes.jpg"},
    {frase: "No tenía nada, lo quise todo, no me importaba lo que costara. Llega la noche en un 530, placa alemana. Si dan el alto 5 chalecos por si disparan", img: "./images/omarMontes.jpg"},
    {frase: "Solo no me via' quedar, por que tu amiga llamando por detrás", img: "./images/omarMontes.jpg"},
    {frase: "Beba qué quieres que haga. Quien la hace riendo, llorando la paga", img: "./images/omarMontes.jpg"},
    {frase: "Ando con una rubia con los ojos de colores, con una morena con tres cargadores", img: "./images/omarMontes.jpg"},
    {frase: "Yo la tengo encadenada en mi cama, como beckyG sin pijama, y yo se la voy a comer na na na na", img: "./images/omarMontes.jpg"},
    {frase: "Marihuana y billetes de 100. Me dejaste loco con un percocet", img: "./images/omarMontes.jpg"},
    {frase: "Criminal, cri-criminal, tu estilo tu flow mami muy criminal", img: "./images/ozuna.jpg"},
    {frase: "Y es que me gustas tú na' mas, no me importan las demás. Una vaina loca que me da, que por más que intento no se va", img: "./images/ozuna.jpg"},
    {frase: "Se pierde en la arena y el mar ah ah ah, estaré soñando yo, se ve tan tropical", img: "./images/ozuna.jpg"},
    {frase: "Bebé, si todavía me amas como antes, ya nada me parece interesante. Yo sé que en el amor soy un farsante, yo sin ti no vuelvo a enamorarme bebé", img: "./images/ozuna.jpg"},
    {frase: "Báilame como si fuera la última vez, y enséñame ese pasito que no sé", img: "./images/ozuna.jpg"},
    {frase: "Hey mor, cómo te saco de aquí. Llego a la disco y sólo pienso en ti, lo que hicimos yo lo quiero olvidar", img: "./images/ozuna.jpg"},
    {frase: "Prendo pa' ver si me olvido de tu nombre, tu besos, tu cuerpo, tus gemidos. Lo hacíamos en el carro me gritaba al oído, cierro los ojos y pienso todo lo que hicimos, baby", img: "./images/ozuna.jpg"},
    {frase: "Prendo un blunt en el punto y se parece a Singapur. Acá no somos Santos todavía somos PXXR", img: "./images/pabloChille.jpg"},
    // {frase: "", img: "./images/pacoA.jpg"},
    {frase: "Tal vez, lo nuestro era solo para divertirse. Pero este tonto suele confundirse y es triste, que del finde ya no a vuelto a sonreirle", img: "./images/pauloLondra.jpg"},
    {frase: "Como Adán y Eva tengamo' nuestro' pecado', Como do' ladrone', un secreto bien guardado", img: "./images/pauloLondra.jpg"},
    {frase: "Con un party en el barrio, siempre hangeando la ganga. Sigue siendo tinto el Escabio, alguna cosas no cambian", img: "./images/pauloLondra.jpg"},
    {frase: "Yo no soy blanco pero soy santo. Tu nena vino porque quiere más rango", img: "./images/peke77.jpg"},
    {frase: "No se le olvida que borracho él le puso los cacho'. No pensó en lo que perdía por dársela de macho", img: "./images/piso21.jpg"},
    {frase: "Un cosplay, bebecita, de Chun-Li. Un bofetón a tu pompa, Will Smith. Móntate en la nave, tunnin' de Need For Speed y es como Icata, está rompiendo en el IG, ja", img: "./images/polimaW.jpg"},
    {frase: "I've been fuckin' hoes and poppin' pillies, man, I feel just like a rockstar", img: "./images/postMalone.jpg"},
    {frase: "Hundred bands in my pocket, it's on me. Hundred deep when I roll like the army. Get more bottles, these bottles are lonely. It's a moment when I show up, got 'em sayin', WOW", img: "./images/postMalone.jpg"},
    {frase: "Guajira, Guantanamera ¿Cuánto me esperas? Punta galera", img: "./images/prok.jpg"},
    {frase: "Fue una bella época, ella mulata. Tocaba las maracas, yo poeta, la llevé a Caracas", img: "./images/prok.jpg"},
    {frase: "Es de Grana' pero parece de La Habana. Vive en la Tierra, pero viene de la luna", img: "./images/prok.jpg"},
    {frase: "Fresas con nata", img: "./images/prok.jpg"},
    {frase: "Me quitao' el disfraz del siglo XXI, ahora voy desnudo nadando por el fondo", img: "./images/prok.jpg"},
    {frase: "Ella es una diabla pa'l tiki-tiki. Yo no me quiero quitar, tiki-tiki. Como se lo hago brincar, tiki-tiki. Mami, rapapam-pam-pam, tiki-tiki", img: "./images/ptazeta.jpg"},
    {frase: "Esa tía 'e la má' chula, no tiene un piquete, lo que ella tiene es un buen piquetón", img: "./images/ptazeta.jpg"},
    {frase: "Mami, mami. E'to 'e por ti, no quiero Grammy. Que e'ta pa' mí, lo sé. Mami y yo pa' ti. E'toy haciendo cash pa' volar de aquí", img: "./images/ptazeta.jpg"},
    {frase: "Trakatá, trakatá esa nena quiere. Trakatá, trakatá, tú quiere'. Trakatá, trakatá, si nos miramo' hace. Takata, traka, hmm, ah", img: "./images/ptazeta.jpg"},
    {frase: "Quédate, que la noche sin ti duele. Tengo en la mente las pose y todos los gemidos. Que ya no quiero nada que no sea contigo", img: "./images/quevedo.jpg"},
    {frase: "Y cada vez que te veo me acuerdo ma' de aquella vez, del perreito en plaza en Playa del Inglés", img: "./images/quevedo.jpg"},
    {frase: "Tú no fuiste la primera, tampoco serás la última. Pero como yo quisiera, que si que fueras la única", img: "./images/quevedo.jpg"},
    {frase: "Parece que olvidaste lo rico que se siente en mi habitación. Tu cuerpo con el mío mai' combinan de una manera, que es vernos, apagar las luces, cámara y acción. Y todo sin meter el corazón ", img: "./images/quevedo.jpg"},
    {frase: "Si te fueras de mi cama sería como LA sin Lebron. Lo tuyo no es genético es un don. Nadie se explica cómo lo mueves tan cabrón", img: "./images/quevedo.jpg"},
    {frase: "Es usted o nadie o yo. La vi perreando y todo se jodió. Te imagino haciendo cosas indebidas. Abra esa boquita y pida", img: "./images/quevedo.jpg"},
    {frase: "A tu familia no le gusto, pero a ti sí. Por eso te robo y si, tu piquete Prada bebe pero yo de DC. De cualquier país serías la missy", img: "./images/quevedo.jpg"},
    {frase: "Que mala suerte, conmigo no quieren verte. Igual no les gusta mi pinta, no tengo nada pa ofrecerte", img: "./images/quevedo.jpg"},
    {frase: "Estaba buscandome en un pary sin señal. Estoy perdido en club buscando donde respirar", img: "./images/quevedo.jpg"},
    {frase: "Tengo a Mami tranquila… la mente tranquila, y la mala vibra “NOT FOUND”. Tengo a la competencia intranquila, aunque los tenga intentando igualar mi SOUND", img: "./images/quevedo.jpg"},
    {frase: "Cuando apagan la luz, no sé si es por su flow o su actitud. Que vaya donde vaya tol' mundo la conoce, ¿de dónde se sacó ese cuerpo? Yo no lo sé", img: "./images/quevedo.jpg"},
    {frase: "Tumba la casa! De sentimientos ahora anda escasa, sale de noche ella no descansa, solo repite si tu no le cansas...", img: "./images/quevedo.jpg"},
    {frase: "Lo que sé es que envidiosas tiene varias, callaíta', callejera y universitaria... Ropa cara para ella no es necesaria, si tiene a la isla detrás desde secundaria", img: "./images/quevedo.jpg"},
    {frase: "Y lo que hace es salir a beber pa' que deje de doler esa herida que no sana. Y como sale to' los días ella convirtió los lunes también en fin de semana", img: "./images/quevedo.jpg"},
    {frase: "Yo tengo claro to' los míos quiénes son. Los que antes no cogían y ahora me tiran al phone", img: "./images/quevedo.jpg"},
    {frase: "Ya cayó la noche. Las gatas se bajaron del coche, ahora toca pecar. Hace que no me conoce, y me la imagino en mil poses al verla bailar", img: "./images/quevedo.jpg"},
    {frase: "En la 42 con la tropi. Cayeron en el bloque un piripiropi. Con kitipo, lo mueve la Popi. Nunca se quitó, horita le rompo ese toti", img: "./images/rauw.jpg"},
    {frase: "Se viste de buena, pero ella es mala. Una gata ganster que te dispara. Ese culo sube y baja como un Impala. Guayando la hebilla terminamos en la sala", img: "./images/rauw.jpg"},
    {frase: "Esa carita me dice que tú eres inquieta, inquieta. Yo no soy tu doctor. Pero tengo aquí tengo la receta, la receta. Ella tiene chocha, culo, teta. La combi completa ", img: "./images/rauw.jpg"},
    {frase: "Excuse me. Ella apretó se hizo nueva las boobies. Ese equipaje aguanta más que una Tumi. Se va a quemar en el break de la uni. Escucha 2/Catorce y Yonaguni", img: "./images/rauw.jpg"},
    {frase: "Me gusta tu olor. De tu piel, el color. Y como me haces sentir", img: "./images/rauw.jpg"},
    {frase: "Contigo quiero despertar. Hacerlo después de fumar. Ya no tengo na' que buscar. Algo fuera de aquí", img: "./images/rauw.jpg"},
    {frase: "Aceleraste mis latidos. Es que me gusta to' de ti. De toas partes, ¿cual decido? Es que me gusta to' de ti…", img: "./images/rauw.jpg"},
    {frase: "Tengo una punto cuarenta. Y una gata pa' perreal, que con ese culo en lo oscuro, te revienta", img: "./images/rauw.jpg"},
    {frase: "Baby, hoy te voy chingal, y al oído vas a gritarme, que siempree me vas amar, y que soy el dueño de todas tus partes", img: "./images/rauw.jpg"},
    {frase: "Tengo reservado el hotel, pero con estas ganas no vamo' a llegar. Somos dos desesperados por eso nos tuvimos que parkear", img: "./images/rauw.jpg"},
    {frase: "Me gustaría tenerte, frecuente. Pero ahora el amor no pasa por mi mente ", img: "./images/rauw.jpg"},
    {frase: "Mi pistola, no tiene seguro, se dispara sola. Es de Barcelona, pero está en Carola. Ella no es seguidora, ella es la ola", img: "./images/rauw.jpg"},
    // {frase: "", img: "./images/recycledJ.jpg"},
    {frase: "Y ahora te me hacé' la divina, cuando te cruzo por la esquina. Y me acuerdo tu' grito', diciendo que yo era tu turrito", img: "./images/rei.jpg"},
    {frase: "Y le gusta mi flow de turro loca e' verme. Yo no le invité un shampú, le invité un fernet", img: "./images/rei.jpg"},
    {frase: "Dímelo Rei. Mami, te traigo receta. No tengo glopeta pero me gané su respect. Tengo la combi completa. La gata, la paca, la chain, una onza de haze", img: "./images/rei.jpg"},
    {frase: "Nena, no puedo. Intentar no quererte una vez más para hacerlo de nuevo. Es que no paro de pensar, mai, en tus labio' y tu cuero", img: "./images/rei.jpg"},
    {frase: "Tu gato te busca en un Fox, yo te busco haciendo whillie con un traje Fox", img: "./images/rei.jpg"},
    {frase: "Ando chipeao, volando bajito. En el R como un hábito, buscando money de young. Voy al corte, llego rápido, voy pisteando obligao, es que ando chipeao", img: "./images/rei.jpg"},
    {frase: "Yo no tengo mil, solo cinco, mis panas. Estoy puesto pa guita, ma, con la mente gitana. Sale por instinto y lo mato sin balas. Se sabe que sin paga entonces no pinta na", img: "./images/rei.jpg"},
    {frase: "Móntate en el carro ponte la chaqueta shorty. Ellos hablan tanto que me da hakeka, yo, niiii. Hacer mil, arde mi cara e ganador. Un rubi, oro si, pagan mi sazon", img: "./images/rei.jpg"},
    {frase: "Ando en la fina, flow pininfarina, salí a la esquina gano la mía crema latina", img: "./images/rei.jpg"},
    {frase: "Mera, bro, yo no soy un parecido. Mi piquete de alta gama, solo me falta el cabrío. Quiero hacerme rico, 'toy lejos del lío. Esquivo malas lengua' con habilidad de Lio (", img: "./images/rei.jpg"},
    {frase: "Lo siento pero, baby. Me mandaron a este mundo pa' quererte. No pa' ver cómo con otro te diviertes", img: "./images/relsB.jpg"},
    {frase: "Qué rico sería. Intercambiar energías. Prender sin decir 'Buenos días'. Hacer el amor y después preguntarte ¿Cómo dormiste, bebé?", img: "./images/relsB.jpg"},
    {frase: "Cuéntame: ¿cómo te va, querida? Por aquí va todo bien, estoy viviendo la vida. ", img: "./images/relsB.jpg"},
    {frase: "No se compra el respeto por ser talentoso, una cosa es ser artista y otra cosa es ser famoso", img: "./images/residente.jpg"},
    {frase: "Esto lo hago pa divertirme", img: "./images/residente.jpg"},
    // {frase: "", img: "./images/residente.jpg"},
    // {frase: "", img: "./images/reykon.jpg"},
    {frase: "Me convencí de que me amabas. Me mentiste mami. Y como un tonto te esperaba. A que vuelvas a mí", img: "./images/rusherking.jpg"},
    {frase: "Se ha puesto la noche rara. Han salio' luna y estrellas. Me lo dijo esa gitana. Mejor no salir a verla", img: "./images/rosalia.jpg"},
    {frase: "Me da miedo cuando sales. Sonriendo pa' la calle. Porque todos pueden ver. Los hoyuelitos que te salen", img: "./images/rosalia.jpg"},
    {frase: "Pienso en tu mirá, tu mirá, clavá, es una bala en el pecho", img: "./images/rosalia.jpg"},
    {frase: "Y átame con tu cabello, a la esquina de tu cama. Que aunque el cabello se rompa, haré ver que estoy atada", img: "./images/rosalia.jpg"},
    {frase: "Pongo rosas sobre el Panamera. Pongo palmas sobre la guantanamera. Llevo a Camarón en la guantera.  Lo hago para mi gente y lo hago a mi manera", img: "./images/rosalia.jpg"},
    {frase: "Esto es pa' que quede, lo que yo hago dura (Con altura). Demasiadas noches de travesura' (Con altura). Vivo rápido y no tengo cura (Con altura). Iré joven pa' la sepultura (Con altura)", img: "./images/rosalia.jpg"},
    {frase: "Rodeá' de flores y billete'. Tamos worldwide a machete. Y mira, bang-bang si con nosotro' te entrometes", img: "./images/rosalia.jpg"},
    {frase: "Cosa' de familia, no la' tienen que escucha'. Lo' capo' con lo' capo' y yo soy la mamá. Los secreto' solo con quien pueda' confia'. Más-más te vale no romper la omertá", img: "./images/rosalia.jpg"},
    {frase: "Es mala amante la fama y no va a quererme de verdad. Es demasia'o traicionera y como ella viene, se me va", img: "./images/rosalia.jpg"},
    {frase: "Pa' ti naki. Chicken teriyaki. Tu gata quiere maki, mi gata en Kawasaki", img: "./images/rosalia.jpg"},
    {frase: "Baby, no me llames. Que yo estoy ocupá, olvidando tus males", img: "./images/rosalia.jpg"},
    {frase: "Ya yo necesito otro beso, uno de esos que tu me das. Estar lejos de ti es el infierno, estar cerca de ti es mi paz", img: "./images/rosalia.jpg"},
    {frase: "Porque la noche de anoche fue. Algo que yo no puedo explicar. Eso era dando y dándole sin parar. Tú me decías que morías por mí", img: "./images/rosalia.jpg"},
    {frase: "", img: "./images/rosalia.jpg"},
    // {frase: "", img: "./images/rosalia.jpg"},
    {frase: "Cuando ella pasa tos las josean, pero ninguno de ellos le vale. Todos la miran si lo menea, cuando ella arranca no hay que la pare", img: "./images/rvfv.jpg"},
    {frase: "Tú loca enamorá de mi, yo también te quería. Pero no supe hacerlo así y ahora mis noches son frías", img: "./images/rvfv.jpg"},
    {frase: "Estoy buscando dinero, mucho money pa' gastar. Si mi gente está en la calle, porque tienen que josear. Mete dinero en la casa, eso si es felicidad. Yo no me acuerdo de nadie que no me quería ayudar", img: "./images/rvfv.jpg"},
    {frase: "Ella no quiere rosé, ella quiere moët. No quiere tabaco, quiere prende'. Dale mami chula, ¿que vamo' hace'?. Dame de tu' beso', beso' de miel", img: "./images/rvfv.jpg"},
    {frase: "Yo no sé qué es lo que pasa, mamá. Que solo me quiere' ver cuando el otro se te va. Y yo no sé lo que hacer, tú a mí me vas a matar. Tú solo piensa' en joder, y yo quiero algo más", img: "./images/rvfv.jpg"},
    {frase: "Y aunque no seas mía. Yo solo quiero que seas tú. Tú eres mi alegría. Si todo se apaga, tú eres mi luz", img: "./images/rvfv.jpg"},
    // {frase: "", img: "./images/santoz.webp"},
    {frase: "Tú te fuiste y desde entonces, más dinero, más culo desde entonces. Chingo más rico desde entonces. Si estas herida pues llama al 911", img: "./images/sech.jpg"},
    {frase: "Y si te vas, tranquila, que esto se olvida. Pasa el tiempo y eso se olvida. Si ni siquiera dura la vida. Bendición, se me cuida", img: "./images/sech.jpg"},
    {frase: "Te cambió siendo mejor que ella, no, no, no. Por mujeres y un par de botellas. Por amigos que no son amigos en verdad. Porque sé que te van a escribir cuando él se va", img: "./images/sech.jpg"},
    {frase: "Cuando el DJ pone la música ella baila como nunca. Y ahora a lo duro y sin disimulo olvidando la pena, la pillé", img: "./images/sech.jpg"},
    {frase: "te dejé en la casa después de hacerlo mami. Pregunta la niña, 3am que hace en línea daddy", img: "./images/sech.jpg"},
    {frase: "No, quiere que vuelva, pero no. No soy un boomerang, no. Que lo tiran y regresa, mami no. Usted se la cagó", img: "./images/sech.jpg"},
    {frase: "Baby si te vas, consigue dos. Igual no van a ser como yo. Pensé que todo se podía y se pudrió. Tranquila por amor nadie se murió.", img: "./images/sech.jpg"},
    {frase: "Ahora todo cambió, le toca a ella- Mari y una botella. Gracias al maltrato se puso bella. Ahora tú la quieres y no te quiere ella", img: "./images/sech.jpg"},
    {frase: "Wao. Siento que me gusta demasiao. Y eso me tiene preocupao. Por que me gusta darle siempre. La tengo en mi cama de Lunes a Viernes", img: "./images/sech.jpg"},
    // {frase: "", img: "./images/sech.jpg"},
    // {frase: "", img: "./images/sech.jpg"},
    // {frase: "", img: "./images/sech.jpg"},
    // {frase: "", img: "./images/sevenKayne.jpg"},
    {frase: "Una loba como yo no está pa novatos. Una loba como yo no está pa tipos como tú", img: "./images/shakira.jpg"},
    {frase: "Te felicito que bien actuas, de eso no me cabe duda. Con tu papel continúa", img: "./images/shakira.jpg"},
    {frase: "No fue culpa tuya, ni tampoco mía. Fue culpa de la monotonía", img: "./images/shakira.jpg"},
    {frase: "Estoy en el bando buscándome el pan, ojos rojos, vengo de Taiwán. Paso a paso, ¿quién me va a parar? Dinero negro, mis Jordan Manchás'", img: "./images/skinnyFlex.jpg"},
    {frase: "Hablas de la calle pero aquí no te vimos, salimos a buscar, luego lo dividimos. Cuatro-cuatro, yo no tengo amigos, juego solo, no confío, primo", img: "./images/skinnyFlex.jpg"},
    {frase: "The ratchets love Snow. Soy la mexicana con tremendo flow. Tengo todo el control. Cierro los ojo', baby, let's go", img: "./images/snow.jpg"},
    {frase: "Estoy acá afuera como un infeliz, abajo de la lluvia pero no quieres abrir. Pensé que me querías pero descubrí, que ahora hay otro más además de mí", img: "./images/tiagoPZK.jpg"},
    {frase: "Perdió las ganas y esta sola , noches con sangre en la boca. Por la culpa de un idiota que su furia desemboca en su ser. Los moretones no los tapa el rímel grita llorando. Y se pregunta “¿por qué?", img: "./images/tiagoPZK.jpg"},
    {frase: "Y si fuera mi estaría cerca de ti. Pero tengo que dejarte volar. Supongo que es una parte de amar", img: "./images/tiagoPZK.jpg"},
    {frase: "Es que cuando nos comemo'. Calladito' y hacemo' que no nos vemo', ey. Tá caliente y no me quemo. Nos rompemo', en la cama. Nos rompemo'", img: "./images/tiagoPZK.jpg"},
    {frase: "Que nos pasó. Que cuando estabamos bien se complicó. Que nos queríamos tanto y ahora no. Cupido tiró la flecha y la cagó. Que le pasó", img: "./images/tini.jpg"},
    {frase: "Hoy salgo con la' muñecas. Volvemo' al amanecer. Se destapan la' botellas. Hoy hay lluvia de Moët", img: "./images/tini.jpg"},
    {frase: "Porque nuestro amor. Esta noche se muere en el bar. Y entonces pásame esa botella. Porque otra boca voy a besar", img: "./images/tini.jpg"},
    {frase: "Dale  miénteme. Haz  lo  que  tú  quieras  conmigo. Dime  que  esta  noche  yo soy  tu  bebé. Y  mañana  somos  amigos", img: "./images/tini.jpg"},
    {frase: "Esto e' para ustede', pa' que se lo gocen. Tego Calderón pa' que retocen", img: "./images/tego.jpg"},
    {frase: "Metele sazón. Batería y reggaeton. Que lo demas lo pone Calderón", img: "./images/tego.jpg"},
    {frase: "Lo mío es punto y aparte. Tírame pa'lante. Calle, pero elegante", img: "./images/tego.jpg"},
    {frase: "Y yo no soy ejemplo mi respeto a tempo. Su único delito fue tener talento", img: "./images/tego.jpg"},
    // {frase: "", img: "./images/tK.webp"},
    {frase: "Le pongo, carácter. TR1 en el marker. Yo hago que lloren, que salten. A la party la parto en partes ", img: "./images/trueno.jpg"},
    {frase: "Ñeri tu bloque me conoce, lo sé. Tiro las guns aunque quemo roses. Si Trueno gana festeja La 12. Yo soy del bajo, vos no sé", img: "./images/trueno.jpg"},
    {frase: "Azul y oro, puestos pa' la música. Somos el brillo dentro de la oscurida'", img: "./images/trueno.jpg"},
    {frase: "Como Pac, todos los ojos puestos en mí. Vivo fact, son leyes, homie.  Mami chula, si queré' voy a buscarte. Que la cima está viniendo por mí", img: "./images/trueno.jpg"},
    // {frase: "", img: "./images/trueno.jpg"},
    {frase: "I'm on the top shelf, I'm such a bombshell. Todo el mundo ve que del Dorado soy la Chel. Todo el mundo quiere un pedazo de mi pastel. Perdía en el mar, soy yo Pi Patel", img: "./images/villano.jpg"},
    {frase: "Aunque pierda, esta gente me va a llenar de orgullo, esa es la diferencia entre mi país y el tuyo", img: "./images/wos.jpg"},
    //{frase: "", img: "./images/wos.jpg"},
    // {frase: "", img: "./images/wisinYYandel.jpg"},
    {frase: "Tú tienes cara de que te gusta freaky y nasty, nada de lo romantic. Tú te ves cara, bitchy, classy, en cuatro fantastic. Más que problematic", img: "./images/youngMiko.jpg"},
    {frase: "Hablando claro, tengo un problema y es que rápido me enchulo de las nenas ", img: "./images/youngMiko.jpg"},
    // {frase: "", img: "./images/youngMiko.jpg"},
    {frase: "Mis ojos mueren con el sol, las flores se alargan. Recojo los frutos que trajo mi Dios, baño mi voz en caña", img: "./images/ysyA.jpg"},
    {frase: "A mi manera de ver todo no hay manera de manchar algo tan puro. Hay un historia que escribir afuera en la que yo vine a poner un punto y coma", img: "./images/ysyA.jpg"},
    {frase: "Puse un barquito en un río, rodeao de navíos. Ma' el mundo ahora es mío", img: "./images/ysyA.jpg"},
    {frase: "La puse a bailar por casi 1g. Si viene por nieve no va a comer,", img: "./images/ysyA.jpg"},
    // {frase: "", img: "./images/ysyA.jpg"},
    // {frase: "", img: "./images/yungBeef.jpg"},
    {frase: "En los espíritus no creo porque nunca vi ninguno, en los fantasmas soy creyente si conozco a mas de uno", img: "./images/zaramay.jpg"},
    {frase: "Me voy pal Nike a buscar prenda' y me piden foto. A 300 en una Cherokee, ella de copiloto", img: "./images/zaramay.jpg"},
    // {frase: "", img: "./images/zaramay.jpg"},
    {frase: "Qué tengo que hacer, pa' que tu seas mi mujer", img: "./images/69.jpg"},
    // {frase: "", img: "./images/69.jpg"},
    
    //farruko, romeoS, jenniferL, el alfa, camilo, randy: hoy se bebe. daviles
    //Yo quiero perrearte y fumarme un blunt. Ver lo que esconde ese pantalón

    /*cambiar foto:
    
    */

]
